#!/usr/bin/env bash
#
# r2kit Release Wizard (v0.2.1)
# Generated by the /wizard skill.
#
# Walks a maintainer step by step through publishing to crates.io and GitHub.

set -euo pipefail

# Anchor execution to repository root
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# ──────────────────────────────────────────────────────────────────────────
# Wizard library
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=6
_STAGE_INDEX=0

# Track actual execution outcomes
CRATE_PUBLISHED=false
TAG_PUSHED=false
RELEASE_CREATED=false
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you through publishing r2kit 0.2.1 step by step.\n' "$DIM"
  printf '  It ensures pre-flight verification, crates.io publishing, Git tagging,\n'
  printf '  and GitHub release creation follow docs/releasing.md safely.%s\n\n' "$RESET"
  pause "Press Enter to start"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "could not open browser automatically; visit: $url"; fi
  } >/dev/null 2>&1 || warn "could not open browser automatically; visit: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

ask_secret() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs input || true
  printf '\n'
  printf -v "$key" '%s' "$input"
}

finish() {
  _clear
  if [[ "$CRATE_PUBLISHED" == true ]]; then
    printf '\n%s%s  ✓ Release v0.2.1 successfully published to crates.io!%s\n\n' "$BOLD" "$GREEN" "$RESET"
    note "• Crate published to crates.io: https://crates.io/crates/r2kit/0.2.1"
  else
    printf '\n%s%s  ⚠ Release wizard finished (crate publication was skipped/failed).%s\n\n' "$BOLD" "$YELLOW" "$RESET"
  fi

  if [[ "$TAG_PUSHED" == true ]]; then
    note "• Git tag pushed to origin: v0.2.1"
  fi

  if [[ "$RELEASE_CREATED" == true ]]; then
    note "• GitHub release created: https://github.com/z0horizon/r2kit/releases/tag/v0.2.1"
  fi

  note "• Docs will be built automatically at: https://docs.rs/r2kit/0.2.1"
  note "• After docs.rs finishes building, verify docs and set repository homepage to https://docs.rs/r2kit/0.2.1"

  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Remaining items to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "r2kit 0.2.1 Release Wizard"

# ── Stage 1: Verify crates.io Credentials ────────────────────────────────
stage "Crates.io Authentication"
say "Check whether Cargo has an active API token for crates.io."
note "If you have already run 'cargo login' on this machine, you can skip entering a token."

if confirm "Do you need to log in to crates.io with a new API token?"; then
  open_url "https://crates.io/settings/tokens"
  step "Generate or copy an API token with 'publish-update' and 'publish-new' scope."
  ask_secret CRATES_TOKEN "Paste your crates.io API token (input is hidden):"
  if [[ -n "$CRATES_TOKEN" ]]; then
    printf '%s\n' "$CRATES_TOKEN" | cargo login
    unset CRATES_TOKEN
    say "✓ Logged in to crates.io successfully."
  else
    unset CRATES_TOKEN
    warn "No token entered; proceeding with existing cargo credentials."
  fi
else
  say "Using existing cargo credentials."
fi
pause

# ── Stage 2: Pre-flight Quality & Package Verification ───────────────────
stage "Pre-flight Quality Verification"
say "Running ./scripts/release-check.sh..."
note "Verifies clean worktree, version match, linting, formatting, full test suite, and package dry-run."

if ./scripts/release-check.sh; then
  say "✓ Pre-flight release check passed cleanly."
else
  warn "Pre-flight release check failed. Fix errors before attempting to release."
  exit 1
fi
pause

# ── Stage 3: Create Local Git Tag ────────────────────────────────────────
stage "Create Local Git Tag"
say "Creating local annotated Git tag: v0.2.1"
note "Following docs/releasing.md: the tag is created locally first, never pushed before publish."

if git rev-parse -q --verify "refs/tags/v0.2.1" >/dev/null; then
  local_tag_commit=$(git rev-parse "refs/tags/v0.2.1^{commit}")
  head_commit=$(git rev-parse HEAD)
  if [[ "$local_tag_commit" == "$head_commit" ]]; then
    say "Local tag 'v0.2.1' already exists and points to HEAD."
  else
    warn "Tag 'v0.2.1' points to $local_tag_commit, but current HEAD is $head_commit."
    if confirm "Recreate tag v0.2.1 to point to current HEAD?"; then
      git tag -f -a v0.2.1 -m "r2kit 0.2.1"
      say "✓ Recreated local tag v0.2.1 pointing to HEAD."
    else
      warn "Aborted to avoid publishing an out-of-sync tag."
      exit 1
    fi
  fi
else
  git tag -a v0.2.1 -m "r2kit 0.2.1"
  say "✓ Created local tag: v0.2.1"
fi
pause

# ── Stage 4: Publish to crates.io ────────────────────────────────────────
stage "Publish to crates.io"
warn "PERMANENT ACTION: A crates.io package cannot be deleted after publishing (only yanked)."
say "We will run: cargo publish --locked"

if confirm "Are you sure you want to publish r2kit 0.2.1 to crates.io?"; then
  if cargo publish --locked; then
    CRATE_PUBLISHED=true
    say "✓ r2kit 0.2.1 has been published to crates.io!"
  else
    warn "cargo publish failed."
    note "Fix the release commit and recreate the local tag before re-running this wizard."
    SKIPPED+=("Resolve cargo publish error and republish: cargo publish --locked")
    exit 1
  fi
else
  warn "Publication aborted by user."
  SKIPPED+=("Publish crate: cargo publish --locked")
  exit 1
fi
pause

# ── Stage 5: Push Git Tag to Remote ──────────────────────────────────────
stage "Push Git Tag to GitHub"
say "Pushing tag 'v0.2.1' to remote 'origin'."
note "Safe to push now that crates.io has accepted the release package."

if confirm "Push git tag v0.2.1 to origin?"; then
  if git push origin v0.2.1; then
    TAG_PUSHED=true
    say "✓ Tag v0.2.1 pushed to origin."
  else
    warn "Failed to push tag to origin."
    SKIPPED+=("Push git tag to origin: git push origin v0.2.1")
  fi
else
  warn "Skipped pushing tag."
  SKIPPED+=("Push git tag to origin: git push origin v0.2.1")
fi
pause

# ── Stage 6: Create GitHub Release ───────────────────────────────────────
stage "Create GitHub Release"
say "Creating GitHub Release with notes extracted from CHANGELOG.md."

RELEASE_TITLE="v0.2.1"

RELEASE_NOTES=$(cat <<'EOF'
### Installation

```toml
[dependencies]
r2kit = "0.2.1"
```

### Highlights

- **Adaptive File Upload**: `Bucket::upload_file(key, path)` automatically selects atomic single PUT for 0-byte and sub-threshold files, and pipelined multipart for files meeting or exceeding the threshold.
- **Configurable Upload Threshold**: Validated `>= 5 MiB` (defaulting to 8 MiB) governing adaptive upload and presigned upload plan dispatch.
- **Unified Presigned Upload Planning**: `Bucket::presign_upload` returning typed `PresignedUploadPlan` (`Single` vs `Multipart`) with preflight offline expiry validation.
- **Direct Abort**: `Bucket::abort_multipart_upload(key, upload_id)` directly aborts multipart uploads without requiring prior snapshot restoration.
- **Stream Ergonomics**: Zero-allocation async object streams via `ListObjectsBuilder::into_stream()` and `into_objects()`, re-exporting `ObjectItem`.
- **Content-Type Ergonomics**: `IntoContentType` trait supporting `&str`, `String`, and `mime::Mime` with offline media-type validation.
- **URL String Accessors**: `.as_str()` and `.into_url_string()` on presigned types while preserving secret signature redaction in `Debug`.
- **Direct Serde Derives**: `MultipartSessionSnapshot` and `UploadThreshold` support direct `Serialize` and `Deserialize` under the `serde` feature flag.
- **0-Byte Upload Fix**: Fixed 0-byte file upload failures caused by S3/R2 multipart uploads rejecting zero-part completions.
- **Canonical Not-Found**: Remote HTTP 404 responses canonically map to `Error::NotFound` with `Error::is_not_found()` helper.
- **Repository Migration**: Updated all repository references to `z0horizon/r2kit`.

See the [Migration Guide (0.2.0 to 0.2.1)](https://github.com/z0horizon/r2kit/blob/main/docs/migration-0.2.1.md) for full details and examples.
EOF
)

if [[ "$TAG_PUSHED" != true ]]; then
  warn "Git tag v0.2.1 has not been pushed to origin. Skipping GitHub release creation."
  SKIPPED+=("Push git tag v0.2.1 and create GitHub Release manually at: https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1")
elif command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Create GitHub Release via gh CLI now?"; then
    if gh release create v0.2.1 --title "$RELEASE_TITLE" --notes "$RELEASE_NOTES"; then
      RELEASE_CREATED=true
      say "✓ GitHub Release created successfully!"
    else
      warn "gh release create failed."
      open_url "https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1"
      SKIPPED+=("Create GitHub release manually: https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1")
    fi
  else
    warn "Skipped GitHub release creation."
    SKIPPED+=("Create GitHub release at: https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1")
  fi
else
  warn "gh CLI not installed or not authenticated."
  open_url "https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1"
  SKIPPED+=("Create GitHub release manually: https://github.com/z0horizon/r2kit/releases/new?tag=v0.2.1")
fi
pause

finish
